contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #sanger-tol-genomeassembly channel"
    url: https://nfcore.slack.com/channels/sanger-tol-genomeassembly
    about: Discussion about the nf-core/sanger-tol-genomeassembly pipeline
