# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/subworkflows/yaml-schema.json
name: "hic_mapping"
description: |
  Maps Hi-C reads in unaligned CRAM format to a set of references.
keywords:
  - hic
  - align
  - bam
components:
  - cramalign/gencramchunks
  - cramalign/bwamem2alignhic
  - cramalign/minimap2alignhic
  - samtools/index:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/faidx:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/merge:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/markdup:
      git_remote: https://github.com/nf-core/modules.git
  - bwamem2/index:
      git_remote: https://github.com/nf-core/modules.git
  - minimap2/index:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_assemblies:
      type: file
      description: |
        Input channel containing assemblies to align Hi-C reads to
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.fn?a(sta)?(.gz)?"
  - ch_hic_cram:
      type: file
      description: |
        Input channel containing Hi-C CRAM files for mapping.
        Structure: [ val(meta), path(cram) ] or [ val(meta), [ path(cram1), path(cram2), ... ] ]
      pattern: "*.cram"
  - val_aligner:
      type: string
      description: Which aligner to use - bwamem2 or minimap2
  - val_cram_chunk_size:
      type: integer
      description: Size of chunk to split CRAM files into
  - val_mark_duplicates:
      type: boolean
      description: Whether to mark duplicates on the merged BAM or not
output:
  - bam:
      type: file
      description: |
        Channel containing the BAM files describing Hi-C alignments to the input assemblies
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@prototaxites"
maintainers:
  - "@prototaxites"
